version: "3.7"
services:
  app:
    container_name: cron-master
    working_dir: /app
    image: groupga/cron-master:local
    expose:
      - '$PORT'
    ports:
      - '$PORT:$PORT'
    command: npm run start
    volumes:
      - app_data:/app
    env_file:
      - .env
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7
    container_name: mysql-server
    restart: always
    environment:
      MYSQL_USER: test
      MYSQL_ROOT_PASSWORD: papapassword
      MYSQL_PASSWORD: test
      MYSQL_DATABASE: crondb
    volumes: 
      - data:/var/lib/mysql
    expose:
      - "3306"
    ports:
      - "3306:3306"

volumes:
  data:
  app_data: